# Generated by Django 4.2.8 on 2023-12-11 16:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.CharField(blank=True, max_length=8)),
                ('name', models.CharField(max_length=80)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('birthDate', models.DateField(default='1970-01-01', null=True)),
                ('deathDate', models.DateField(blank=True, default='1970-01-01', null=True)),
                ('image', models.ImageField(default='actors_images/default_image.jpg', null=True, upload_to=home.models.actor_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png'])])),
            ],
        ),
        migrations.CreateModel(
            name='ActorMovieRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actormovierole_id', models.CharField(blank=True, max_length=8)),
                ('character', models.CharField(max_length=100)),
                ('actors', models.ManyToManyField(related_name='actor_roles', to='home.actor')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(blank=True, max_length=4)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_id', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Serieses',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(blank=True, max_length=6)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('trailerVideo', models.FileField(null=True, upload_to=home.models.trailer_video_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('image', models.ImageField(null=True, upload_to=home.models.movie_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png'])])),
                ('fontFamily', models.CharField(max_length=100)),
                ('ageLimit', models.CharField(blank=True, max_length=10, null=True)),
                ('length', models.IntegerField()),
                ('year', models.IntegerField()),
                ('rating', models.FloatField()),
                ('ratingsCount', models.IntegerField(default=0)),
                ('actor_roles', models.ManyToManyField(related_name='actor_roles', to='home.actormovierole')),
                ('categories', models.ManyToManyField(related_name='movies', to='home.category')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.series')),
            ],
        ),
    ]
